version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: /src/backend/Dockerfile
    container_name: trip_backend
    env_file: src/backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: trip_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: trip_db
    restart: always
    env_file:
      - ./src/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
